SET CGO_ENABLED=0
SET GOOS=android
SET GOARCH=amd64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\android\tcp_over_ws_amd64"
SET GOOS=android
SET GOARCH=arm
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\android\tcp_over_ws_arm"
SET GOOS=android
SET GOARCH=arm64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\android\tcp_over_ws_arm64"
SET GOOS=darwin
SET GOARCH=amd64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\darwin\tcp_over_ws_amd64"
SET GOOS=darwin
SET GOARCH=arm64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\darwin\tcp_over_ws_arm64"
SET GOOS=ios
SET GOARCH=amd64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\ios\tcp_over_ws_amd64"
SET GOOS=ios
SET GOARCH=arm64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\ios\tcp_over_ws_arm64"
SET GOOS=linux
SET GOARCH=386
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\tcp_over_ws_386"
SET GOOS=linux
SET GOARCH=amd64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\tcp_over_ws_amd64"
SET GOOS=linux
SET GOARCH=arm
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\tcp_over_ws_arm"
SET GOOS=linux
SET GOARCH=arm64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\tcp_over_ws_arm64"
SET GOOS=linux
SET GOARCH=mips
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\tcp_over_ws_mips"
SET GOOS=linux
SET GOARCH=mips64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\tcp_over_ws_mips64"
SET GOOS=linux
SET GOARCH=mips64le
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\tcp_over_ws_mips64le"
SET GOOS=linux
SET GOARCH=mipsle
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\tcp_over_ws_mipsle"
SET GOOS=linux
SET GOARCH=ppc64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\tcp_over_ws_ppc64"
SET GOOS=linux
SET GOARCH=ppc64le
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\tcp_over_ws_ppc64le"
SET GOOS=linux
SET GOARCH=riscv64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\tcp_over_ws_riscv64"
SET GOOS=linux
SET GOARCH=s390x
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\linux\tcp_over_ws_s390x"
SET GOOS=windows
SET GOARCH=386
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\windows\tcp_over_ws_386.exe"
SET GOOS=windows
SET GOARCH=arm
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\windows\tcp_over_ws_arm.exe "
SET GOOS=windows
SET GOARCH=arm64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\windows\tcp_over_ws_arm64.exe"
SET GOOS=windows
SET GOARCH=amd64
go build -a -trimpath -asmflags "-s -w" -ldflags "-s -w -buildid=" -o "build\windows\tcp_over_ws_amd64.exe"
pause
